// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqPWh-mAXBYMUpJ5fgY5Fj6LAzp35Qfgc',
    appId: '1:968576878838:web:e196b4dfdd1c58e68584d7',
    messagingSenderId: '968576878838',
    projectId: 'betamigo-d49f9',
    authDomain: 'betamigo-d49f9.firebaseapp.com',
    storageBucket: 'betamigo-d49f9.appspot.com',
    measurementId: 'G-8B6G5GJ764',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0vMTptJ_TUAdzI5du-fHsv_DV_oFQdQs',
    appId: '1:968576878838:android:07359a0cc4abc7688584d7',
    messagingSenderId: '968576878838',
    projectId: 'betamigo-d49f9',
    storageBucket: 'betamigo-d49f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQlBH2PzJamuAYi8NRw3zXLXUx-l19l8E',
    appId: '1:968576878838:ios:35a0b7a98b5f16178584d7',
    messagingSenderId: '968576878838',
    projectId: 'betamigo-d49f9',
    storageBucket: 'betamigo-d49f9.appspot.com',
    iosBundleId: 'com.example.betamigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQlBH2PzJamuAYi8NRw3zXLXUx-l19l8E',
    appId: '1:968576878838:ios:e3aa0170d8782d1c8584d7',
    messagingSenderId: '968576878838',
    projectId: 'betamigo-d49f9',
    storageBucket: 'betamigo-d49f9.appspot.com',
    iosBundleId: 'com.example.betamigo.RunnerTests',
  );
}
